### ISSUE TITLE
Can't download OSCAR 23.01 corpus (at least Japanese portion of it) via `dodc`

### ISSUE THREAD

**Issue by fujiki-lemon** [oscar-project/download_oscar#10]
Problem
---
Thank you for releasing OSCAR 23.01.
I'm a Japanese user and would like to use the new OSCAR.

But I got an error while I'm trying to download the files by using `dodc` command.
Specifically, I tried `dodc` command like bellow, but the `results.txt` was empty.
```
$ dodc --user ${USER} --password ${PASSWORD}  --base_url https://oscar-prive.huma-num.fr/2301/ja_meta/ --out oscar-2301/
Files: : 0it [00:00, ?it/s]
```
When looking inside the output file named `results.txt`, it says
```
$ cat oscar-2301/results.txt
{}
```

How can I successfully download the OSCAR 23.01 dataset by `dodc`?

Background
---
I have an account at `oscar-prive.huma-num.fr` and I can access the site without error.
And I can download manually from the URL.

When I download OSCAR 22.01 by `dodc`, it seems that I can download the files.
Specifically,
```
$ dodc --user ${USER} --password ${PASSWORD} --base_url https://oscar-prive.huma-num.fr/2201/packaged/ja_meta/ --out oscar-2201

Files:   0%|                                                | 0/259 [00:00<?, ?it/s]
oscar-2201/ja_meta_part_132.jsonl.gz:  91%|███▋| 273M/301M [00:09<00:00, 32.6MB/s]
```
```
$ ls oscar-2201
ja_meta_part_132.jsonl.gz  results.txt
```

---
It'd be really appreciated if you could help me with this issue.
Thanks in advance.

By the way, I'm not very familiar with writing issues, so if you find something incovenient for solving this issue, please let me know.
I'll try to write a better issue as possible as I can.

**Comment by xamm** [comment]
Hi and thanks for opening this issue.
The problem seems to be a check for specific file extensions.
In OSCAR 23.01 the file extension has changed, but is not included in the extensions to download.
I added PR #11 which should enable downloading OSCAR 23.01

**Comment by fujiki-lemon** [comment]
Thanks for your quick work.

> In OSCAR 23.01 the file extension has changed

changed to `.zst`, right?
Anyway, I'm now able to be downloading the files.
```
$ dodc --user ${USER} --password ${PASSWORD}  --base_url https://oscar-prive.huma-num.fr/2301/ja_meta/ --out oscar-2301

Files:   0%|                                                | 0/123 [00:00<?, ?it/s]
oscar-2301_1/ja_meta_part_37.jsonl.zst:  25%|█   | 151M/601M [00:05<00:13, 34.8MB/s]
```
Thanks.
